apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-web
  name: {{ .Release.Name }}-web
  annotations:
    metallb.io/allow-shared-ip: "pihole-key-192-168-1-3"
    metallb.io/loadbalancerIP: 192.168.1.3
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: "{{ .Release.Name }}-pihole"
