apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-ingressroute
  namespace: pihole
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`pihole.local.rubenclaessens.nl`)
      priority: 10
      services:
        - name: pihole-web
          port: 80
  tls:
    secretName: local-rubenclaessens-nl-tls-production
